#!/usr/bin/env python3
"""
Merge Rule Mapping Data into Allure Categories Trend

This script calculates Rule Mapping statistics from test-results.json and
MERGES them into the existing categories-trend.json generated by Allure CLI.

Key behavior:
- Does NOT create new entries for the current build
- MERGES Rule Mapping data into the existing entry with the same buildOrder
- Prevents duplicate entries

Adapted from falco-plugin-nginx for openclaw's test-results.json format.

Usage:
    python generate_rule_mapping_trend.py \
        --test-results results/test-results.json \
        --run-number 100 \
        --report-url "https://example.com/100/" \
        --history-input allure-report/history/categories-trend.json \
        --history-output allure-report/history/categories-trend.json \
        --max-history 20
"""

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger(__name__)

CATEGORY_MATCH = "Rule Match"
CATEGORY_MISMATCH = "Rule Mismatch"
CATEGORY_EXPECTED_NOT_DETECTED = "Expected Not Detected"
CATEGORY_NOT_DEFINED = "Not Defined"


def calculate_rule_mapping_status(test_result: Dict) -> str:
    """Calculate Rule Mapping status for a single test result.

    Openclaw-specific logic based on category, expected_rule, and rule_match fields.
    """
    category = test_result.get("category", "")
    expected_rule = test_result.get("expected_rule", "")
    rule_match = test_result.get("rule_match") is True

    if category == "benign" and not expected_rule:
        return CATEGORY_EXPECTED_NOT_DETECTED

    if not expected_rule:
        return CATEGORY_NOT_DEFINED

    if rule_match:
        return CATEGORY_MATCH

    return CATEGORY_MISMATCH


def calculate_statistics(test_results: List[Dict]) -> Dict[str, int]:
    """Calculate Rule Mapping statistics from test results."""
    stats = {
        CATEGORY_MATCH: 0,
        CATEGORY_MISMATCH: 0,
        CATEGORY_EXPECTED_NOT_DETECTED: 0,
        CATEGORY_NOT_DEFINED: 0,
    }
    for result in test_results:
        status = calculate_rule_mapping_status(result)
        stats[status] += 1
    return stats


def merge_trend_history(
    run_number: int,
    stats: Dict[str, int],
    existing_history: List[Dict],
    report_url: str = "",
    max_history: int = 20,
) -> List[Dict]:
    """Merge Rule Mapping stats into existing history entry with same buildOrder."""
    updated = list(existing_history)
    found_existing = False

    for entry in updated:
        if entry.get("buildOrder") == run_number:
            if "data" not in entry:
                entry["data"] = {}
            entry["data"].update(stats)
            if entry.get("reportName") == "Allure Report":
                entry["reportName"] = f"E2E Tests #{run_number}"
            if not entry.get("reportUrl") and report_url:
                entry["reportUrl"] = report_url
            found_existing = True
            logger.info(f"Merged Rule Mapping data into existing entry for build #{run_number}")
            break

    if not found_existing:
        new_entry = {
            "buildOrder": run_number,
            "reportName": f"E2E Tests #{run_number}",
            "reportUrl": report_url,
            "data": stats,
        }
        updated.insert(0, new_entry)
        logger.info(f"Created new entry for build #{run_number}")

    updated.sort(key=lambda x: x.get("buildOrder", 0), reverse=True)
    return updated[:max_history]


def main():
    parser = argparse.ArgumentParser(
        description="Merge Rule Mapping data into Allure Categories Trend"
    )
    parser.add_argument("--test-results", required=True, help="Path to test-results.json")
    parser.add_argument("--run-number", type=int, required=True, help="Run number")
    parser.add_argument("--report-url", default="", help="URL to the Allure report")
    parser.add_argument("--history-input", help="Path to existing categories-trend.json")
    parser.add_argument("--history-output", required=True, help="Output path")
    parser.add_argument("--max-history", type=int, default=20, help="Max entries")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    test_results_path = Path(args.test_results)
    if not test_results_path.exists():
        logger.error(f"Test results file not found: {args.test_results}")
        sys.exit(1)

    with open(test_results_path, "r") as f:
        test_results = json.load(f)
    logger.info(f"Loaded {len(test_results)} test results")

    stats = calculate_statistics(test_results)
    logger.info(f"Rule Mapping Statistics: {stats}")

    existing_history = []
    if args.history_input:
        history_path = Path(args.history_input)
        if history_path.exists():
            try:
                with open(history_path, "r") as f:
                    existing_history = json.load(f)
                logger.info(f"Loaded {len(existing_history)} existing entries")
            except (json.JSONDecodeError, IOError) as e:
                logger.warning(f"Could not load history: {e}")

    updated_history = merge_trend_history(
        run_number=args.run_number,
        stats=stats,
        existing_history=existing_history,
        report_url=args.report_url,
        max_history=args.max_history,
    )

    output_path = Path(args.history_output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(updated_history, f, indent=2)
    logger.info(f"Written {len(updated_history)} entries to {args.history_output}")

    total = sum(stats.values())
    match_rate = (stats[CATEGORY_MATCH] / total * 100) if total > 0 else 0
    print(f"\n{'='*50}")
    print("Rule Mapping Data Merged into Categories Trend")
    print(f"{'='*50}")
    print(f"Run Number: {args.run_number}")
    print(f"Total Patterns: {total}")
    print(f"  - {CATEGORY_MATCH}: {stats[CATEGORY_MATCH]}")
    print(f"  - {CATEGORY_MISMATCH}: {stats[CATEGORY_MISMATCH]}")
    print(f"  - {CATEGORY_EXPECTED_NOT_DETECTED}: {stats[CATEGORY_EXPECTED_NOT_DETECTED]}")
    print(f"  - {CATEGORY_NOT_DEFINED}: {stats[CATEGORY_NOT_DEFINED]}")
    print(f"Match Rate: {match_rate:.1f}%")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
